/* Generated By:JJTree&JavaCC: Do not edit this line. TreePatternParserConstants.java */
package fr.inria.oak.paxquery.common.xml.navigation.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TreePatternParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int ATTRDOCID = 8;
  /** RegularExpression Id. */
  int ATTRID = 9;
  /** RegularExpression Id. */
  int ATTRVAL = 10;
  /** RegularExpression Id. */
  int ATTRCONT = 11;
  /** RegularExpression Id. */
  int PREDCODE = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<INTEGER_LITERAL>",
    "<STRING>",
    "\"docID\"",
    "\"ID\"",
    "\"Val\"",
    "\"Cont\"",
    "<PREDCODE>",
    "\";\"",
    "\"/\"",
    "\"o\"",
    "\"O\"",
    "\"[Namespace=\"",
    "\"]\"",
    "\"E:\"",
    "\"A:\"",
    "\"s\"",
    "\"i\"",
    "\"n\"",
    "\"u\"",
    "\"R\"",
    "\"[Tag=\"",
    "\"Tag\"",
    "\"[Val\"",
    "\",\"",
    "\"//\"",
    "\"j\"",
  };

}
