/* Generated By:JavaCC: Do not edit this line. XParserConstants.java */
package fr.inria.oak.paxquery.xparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IntegerLiteral = 34;
  /** RegularExpression Id. */
  int DecimalLiteral = 35;
  /** RegularExpression Id. */
  int StringLiteral = 36;
  /** RegularExpression Id. */
  int QNameToken = 37;
  /** RegularExpression Id. */
  int NCNameTok = 38;
  /** RegularExpression Id. */
  int Digits = 39;
  /** RegularExpression Id. */
  int LocalPart = 40;
  /** RegularExpression Id. */
  int Nmstart = 41;
  /** RegularExpression Id. */
  int Nmchar = 42;
  /** RegularExpression Id. */
  int Letter = 43;
  /** RegularExpression Id. */
  int BaseChar = 44;
  /** RegularExpression Id. */
  int Ideographic = 45;
  /** RegularExpression Id. */
  int CombiningChar = 46;
  /** RegularExpression Id. */
  int Digit = 47;
  /** RegularExpression Id. */
  int Extender = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\";\"",
    "\"or\"",
    "\"and\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"div\"",
    "\"mod\"",
    "\"|\"",
    "\"/\"",
    "\"//\"",
    "\"@\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"text\"",
    "\"concat\"",
    "\"substring\"",
    "\"not\"",
    "\"floor\"",
    "\"ceiling\"",
    "\"true\"",
    "\"false\"",
    "<IntegerLiteral>",
    "<DecimalLiteral>",
    "<StringLiteral>",
    "<QNameToken>",
    "<NCNameTok>",
    "<Digits>",
    "<LocalPart>",
    "<Nmstart>",
    "<Nmchar>",
    "<Letter>",
    "<BaseChar>",
    "<Ideographic>",
    "<CombiningChar>",
    "<Digit>",
    "<Extender>",
  };

}
